[game]
hostname = "[MRP][RU]⚜️Victoria - оплот истории вселенной"
desc = "📕  Victoria — это активно развивающийся сервер с требованиями к отыгрышу MRP+, базирующийся собственной на проработанной вселенной.\n________________________________________\nУНИКАЛЬНЫЕ МЕХАНИКИ:\n🍄 Токсикология;\n🔬 Материаловедение;\n🎓 Новые роли;\n🌐 Неигровые персонажи (НПС);\n📈  Корпоративные поставки;\n⭐ И многое другое!"
map_pool = "VictoriaDefaultMapPool"
maxplayers = 120
soft_max_players = 100
map_rotation = true
role_timers = false

[infolinks]
discord = "https://discord.gg/M7GREWUKcs"
boosty = "https://boosty.to/ss14_victoria"

[server]
rules_file = "VictoriaRuleset"

[viewport]
maximum_width = 29

[game.panic_bunker]
enabled = false
show_reason = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
enable_without_admins = false
disable_with_admins = false

[rules]
time = 90

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e"
